export const productData = [
    {
        id: "1",
        product_name: "Noise-Cancelling Headphones",
        product_description: "Wireless Noise-Cancelling Headphones with 20h Battery Life",
        price: 199.99,
        image: "https://dummyimage.com/600x400/000/fff&text=Headphones",
        status: "IN_STOCK",
        category: "Electronics",
    },
    {
        id: "2",
        product_name: "Ergonomic Office Chair",
        product_description: "Ergonomic Mesh Office Chair with Lumbar Support",
        price: 149.5,
        image: "https://dummyimage.com/600x400/000/fff&text=Chair",
        status: "OUT_OF_STOCK",
        category: "Furniture",
    },
    {
        id: "3",
        product_name: "Mechanical Keyboard",
        product_description: "Mechanical Gaming Keyboard - RGB Backlit",
        price: 89.99,
        image: "https://dummyimage.com/600x400/000/fff&text=Keyboard",
        status: "COMING_SOON",
        category: "Electronics",
    },
    {
        id: "4",
        product_name: "Thermal Water Bottle",
        product_description: "Stainless Steel Thermal Water Bottle (1L)",
        price: 25.0,
        image: "https://dummyimage.com/600x400/000/fff&text=Bottle",
        status: "IN_STOCK",
        category: "Lifestyle",
    },
    {
        id: "5",
        product_name: "Ceramic Coffee Set",
        product_description: "Ceramic Pour-Over Coffee Maker Set",
        price: 500,
        image: "https://dummyimage.com/600x400/000/fff&text=Coffee",
        status: "IN_STOCK",
        category: "Kitchen",
    },
];
